### ISSUE TITLE
Add ability to try to determine variant index from a package request

### ISSUE THREAD

**Issue by captainhammy** [captainhammy/build-rez-package-action#2]
Consider the following situation:

- I have a package with variants for different Houdini versions
- I want to build and test this package using a matrix of docker images (1 for each Houdini version)

How do I structure my tests action to choose the correct variant based on the Houdini version of the image I am using?

Right now this is possible if we did something like the following and used the extra `variant` item to drive the actino parameter:
```yaml
matrix:
    houdini-version: ["20.5", "20.0"]
    include:
      - houdini-version: "20.0"
        variant: 0
      - houdini-version: "20.5"
        variant: 1
```

A perhaps more useful alternative would be to allow this action to take an optional package request item that could be matched against the package's variant requiers to determine the appropriate variant number:

```yaml
  - name: Build Package
    uses: captainhammy/build-rez-package-action@v1
    with:
      variant-from-request: houdini-${{ matrix.houdini-version }}
```

In this case, the action would check the target package's variants and attempt to find one which had a requirement that matched the requested package-version. If so, that variant would be the one that is built.

If a user provides the `variant` value and the `variant-from-request`, the `variant` will win out.
